### ISSUE TITLE
Add some more Tips and Tricks entries

### ISSUE THREAD

**Issue by Consolatis** [labwc/labwc.github.io#15]
- [x] Use `A-Tab` and friends via VNC / VM / nested compositor (https://github.com/labwc/labwc/issues/810#issuecomment-1452153012)
- [x] run_or_raise.sh (https://github.com/labwc/labwc/issues/673#issuecomment-1358025228)
- [x] Link wlroots env vars: https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/docs/env_vars.md
- more?

**Comment by johanmalm** [comment]
^ Sounds great.
