### ISSUE TITLE
Add a `Troubleshooting` section?

### ISSUE THREAD

**Issue by Consolatis** [labwc/labwc.github.io#19]
It could mention for example adding `WLR_NO_HARDWARE_CURSORS=1` to `~/.config/labwc/environment` when starting labwc only results in a black screen with no obvious way to interact. Seems to happen on vmware but might also happen on other system configurations with broken hardware cursors.

Edit:
Cursor issues (cursor doesn't update, looks ugly): `XCURSOR_THEME=Adwaita` set and Adwaita cursor theme installed?

**Comment by johanmalm** [comment]
See https://github.com/labwc/labwc.github.io/pull/23
