### ISSUE TITLE
Update margin description to include it being a workaround and usually not required

### ISSUE THREAD

**Issue by Consolatis** [labwc/labwc.github.io#37]
https://labwc.github.io/labwc-config.5.html#margin

- state its use-case as a workaround for panels not supporting layershell (didn't we have that somewhere before?)
- define the word "output" more clearly
- mention that leaving out the output argument (rather than leaving it an empty string) applies the margin to all outputs

**Comment by johanmalm** [comment]
https://github.com/labwc/labwc/pull/1302

**Comment by Consolatis** [comment]
:)
